### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by loonix** [pschwede/musiccn#1]
Hi there,

Will you be able to paste the db as well? looks great so far!

**Comment by pschwede** [comment]
I didn't touch this project since years. However I'll try to recover what you need. Did you try calling install.php?

**Comment by loonix** [comment]
I tried but doesn't seem to work not sure if I forgot to do someting

**Comment by pschwede** [comment]
The code was/is buggy. I updated the parts that cause install.php to fail. Please, update your repo and try again.

edit: you find the credentials for MySQL access in libs/database.php

**Comment by loonix** [comment]
Hi there,

The code has some bugs but don't worry, I will keep it as reference for my future projects.Many thanks great work!
